baseURL = "https://hugo101.netlify.com/"
languageCode = "en-us"
title = "Hugo 101"
theme = "hugo-base16-theme"

[backend]
name = "github"
repo = "jgreidy/hugo101" # Path to your GitHub repository
# optional, defaults to master
# branch: main